### ISSUE TITLE
ReadOnly and "null" as value does not work

### ISSUE THREAD

**Issue by dve** [mstahv/v-leaflet-editable#6]
When having an empty PolygonField set readOnly does not work correct, drawing is still allowed.
I will check if also other fields are affected and provide a pull request

**Comment by dve** [comment]
The issue occurres on all sub classes of `AbstractEditableJTSField`. It seams that `getEditableMap().remove()` is not working immediately, even if `setImmediatly(true)` is called.
If you switch between the tabs in the demo, it works fine.

@mstahv any idea how to remove the exension immediately? `markAsDirty()` did not have the effect

**Comment by mstahv** [comment]
I'll fix this in a moment...

**Comment by mstahv** [comment]
Pushed out 1.0.1 with the fix, let me know if it don't work.
