### ISSUE TITLE
FeatureModifiedEvent get wrongly fired when UI is updated and when PULL/PUSH is used.

### ISSUE THREAD

**Issue by thomasmulticap3** [mstahv/v-leaflet-editable#9]
It seems when LEditable is created and a FeatureModifiedListener is added, and editing of a vector has thus started on the client side, the FeatureModifiedEvent gets wrongly fired whenever another action in the GUI is notified to the backend (ex. ClickEvent on a button, LeafletMouseOverEvent, etc.).

Also, whenever server poll is used in the UI (setServerPollInterval), the events also gets fired when editing was still ongoing on the client side, even when no UI update is pending. This causes editing to stop prematurely. The same goes for Vaadin Push. Whenever a UI update is pushed, editing stops.

What can be done to prevent this? Or does this indicate a bug in the event firing?

**Comment by mstahv** [comment]
Finally had a chance to look into this. The V8 compatible 2.0 version now works correctly here. I needed to add some changes for the v-leaflet project as well to get it properly fixed.

If you need it for the V7 version, should do similar changes for v-leaflet V7 branch.
